ALTER TABLE Users DROP CONSTRAINT PK_Id_Username
ALTER TABLE Users ADD CONSTRAINT PK_Users_Id PRIMARY KEY(Id)
ALTER TABLE Users ADD CONSTRAINT UC_UsernameUnique UNIQUE (Username)
ALTER TABLE Users ADD CONSTRAINT UC_UsernameThreeCharsLong CHECK(LEN(Username) > 3)