INSERT INTO Towns([Name]) VALUES ('Sofia')
INSERT INTO Towns([Name]) VALUES ('Plovdiv')
INSERT INTO Towns([Name]) VALUES ('Varna')
INSERT INTO Towns([Name]) VALUES ('Burgas')

INSERT INTO Departments([Name]) VALUES ('Engineering')
INSERT INTO Departments([Name]) VALUES ('Sales')
INSERT INTO Departments([Name]) VALUES ('Marketing')
INSERT INTO Departments([Name]) VALUES ('Software Development')
INSERT INTO Departments([Name]) VALUES ('Quality Assurance')