CREATE DATABASE OnlineStore

CREATE TABLE Orders
(
	OrderID INT PRIMARY KEY,
	CustomerID INT
)

CREATE TABLE Customers
(
	CustomerID INT PRIMARY KEY,
	[Name] VARCHAR(50),
	Birthday DATE,
	CityID INT
)

CREATE TABLE Cities
(
	CityID INT PRIMARY KEY,
	[Name] VARCHAR(50)
)

CREATE TABLE Items
(
	ItemID INT PRIMARY KEY,
	[Name] VARCHAR(50),
	ItemTypeID INT
)

CREATE TABLE OrderItems
(
	OrderID INT FOREIGN KEY REFERENCES Orders(OrderID),
	ItemID INT FOREIGN KEY REFERENCES Items(ItemID),
	CONSTRAINT PK_OrderItems PRIMARY KEY (OrderID, ItemID)
)

CREATE TABLE ItemTypes
(
	ItemTypeID INT PRIMARY KEY,
	[Name] VARCHAR(50)
)

ALTER TABLE Orders ADD CONSTRAINT FK_Orders FOREIGN KEY (CustomerID) REFERENCES Customers (CustomerID)
ALTER TABLE Customers ADD CONSTRAINT FK_Customers FOREIGN KEY (CityID) REFERENCES Cities (CityID)
ALTER TABLE Items ADD CONSTRAINT FK_Items FOREIGN KEY (ItemTypeID) REFERENCES ItemTypes (ItemTypeID)